### ISSUE TITLE
日付で”今日”を選択したとき前日になる問題

### ISSUE THREAD

**Issue by Owaowata252** [kiimLab/drunk-alpaca#1]
入構申告のmodalで今日を選択した場合，UTC+0が参照され日付が前日になる
- 例
```
朝8:00に記入 -> -9:00され前日に(23:00)
```
原因としては[こちら](https://qiita.com/labocho/items/5fbaa0491b67221419b4#json-%E3%81%AB%E3%81%99%E3%82%8B%E3%81%A8%E6%97%A5%E4%BB%98%E3%81%8C%E5%A4%89%E3%82%8F%E3%82%8B%E3%81%93%E3%81%A8%E3%81%8C%E3%81%82%E3%82%8B)が考えられます．

誰かデバッグお願いします^_^

**Comment by onohi26** [comment]
コンソールの出力は9時間前になっていますが日付が変わってから上記内容を実行してみたところスプレッドシートの出力は正常でしたので問題ないかと思います。
