### ISSUE TITLE
日付表記の年度を消去する

### ISSUE THREAD

**Issue by kopokopo1711** [kiimLab/drunk-alpaca#6]

**Comment by Owaowata252** [comment]
年度を消去するついでに表記も変えてほしいです。

現在`2020-11-01`となっているのを`11/01`もしくは`11月01日`みたいな感じで

どの表記をするかはお任せします。

**Comment by kopokopo1711** [comment]
gas内で日付から頭5文字を消去しました。
これにてクローズします。
